package com.example.asus.senjatakhasindonesia;

import java.util.ArrayList;

public class SenjataData {
    public static String[][] data = new String[][]{
            {"Rencong", "Aceh", "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/COLLECTIE_TROPENMUSEUM_IJzeren_lemmet_met_houten_met_schede_TMnr_1662-1.jpg/350px-COLLECTIE_TROPENMUSEUM_IJzeren_lemmet_met_houten_met_schede_TMnr_1662-1.jpg", "Menurut catatan sejarah, Rencong merupakan senjata tradisional yang digunakan di Kesultanan Aceh sejak masa pemerintahan Sultan Ali Mughayat Syah yang merupakan Sultan Aceh yang pertama. Kedudukan Rencong di Kesultanan Aceh sangatlah penting, Rencong selalu diselipkan di pinggang Sultan Aceh, selain itu para Ulee Balang dan masyarakat biasa juga menggunakan Rencong. Rencong emas milik Sultan Aceh dapat kita jumpai di Museum Sejarah Aceh, dari bukti sejarah tersebut dapat disimpulkan bahwa Rencong memang sudah terlahir sejak masa Kesultanan Aceh namun pembuat pertamanya sampai saat ini belum diketahui."},
            {"Piso Halasan", "Sumatra Utara", "https://image.invaluable.com/housePhotos/czernyintl/78/625478/H2672-L143845587.jpg", "Piso Halasan adalah pedang yang berasal dari Tapanuli Utara Batak Sumatra Utara. Piso Halasan biasanya dimiliki seorang pemimpin batak yang sudah memiliki otoritas hingga di tingkat Bius.\n" + "\n" + "Piso Halasan adalah lambang kebesaran Orang Batak hasangapon bagi dirinya yang membawa manfaat bagi orang banyak. Menegakkan hukum yang adil dan memberi jalan kehidupan bagi warga. Mereka cerdas, namum mampu membatasi diri untuk tidak terjerumus kepada kepentingan pribadi. Pola pikirnya tajam (piso) mencari solusi dalam setiap permasalahan dan memperluas wawasan mencari peluang untuk kesejahteraan. Pisau adalah lambang kecerdasan, dan sarungnya adalah hukum yang melakukan solam pembatasan dari hal yang menjerumuskannya kepada perbuatan yang dapat merugikan masyarakat.\n" +
                    "\n" + "Semua hasil pemikiran, tindakan pemimpin akan bermanfaat untuk orang banyak, kerukunan, kedamaian, kesejahteraan yang menjadi (halasan) kesenangan yang lebih berarti, kebahagiaan."},
            {"Pedang Jenawi", "Riau", "https://media.sketchfab.com/urls/7896d3210f0e4e9495a1a2430967f463/dist/thumbnails/9e429ce923c14f19953ba0b1dd97d3f0/0c8bbafbaf0243c7a3e1e2b2772d70a3.jpeg", "Provinsi Riau memiliki senjata tradisional yang bernama Pedang Jenawi. Pemakai Pedang Jenawi pastilah orang yang memiliki kekuasaan, orang yang dihormati, memiliki kecerdasan, sehingga menjadi panutan, dan sebagainya. Pedang Jenawi memiliki ketajaman di tiga sisi, yakni bagian kanan, kiri, dan depan. Pedang ini adalah sebuah pedang panjang yang bilahnya terbuat dari baja. Bentuk bilahnya sendiri lurus dan meruncing di bagian ujungnya. Pedang Jenawi dulunya digunakan para panglima perang Kerajaan Sriwijaya sebagai sarana perlindungan diri dan alat menyerang lawan. Keberadaannya kini mulai langka, padahal semakin banyak kolektor senjata tradisional yang selama ini terus memburunya."},
            {"Karih", "Sumatra Barat", "https://2.bp.blogspot.com/-MYYQw1dRGpc/WuCPKz8y11I/AAAAAAAABM8/_69NJsv1AfUojmXzHGWEzMMcRZYJmIXZgCLcBGAs/s1600/senjata%2Btradisional%2Bsumatera%2Bbarat%2Bkarih.jpg", "Suku Minang di Sumatra Baratt memiliki senjata tradisional yang bernama Karih. Karih adalah sebuah senjata berbentuk seperti keris tapi tidak memiliki lekuk-lekukan seperti keris di Jawa. Dahulunya, Karih digunakan untuk perlindungan diri dari musuh atau binatang buas saat para pria tengah bekerja.\n" +
                    "\n" + "Karih / Keris ini merupakan perlengkapan / aksesoris yang dipakai oleh kaum laki-laki dan diletakkan di sebelah depan, dan umumnya dipakai oleh para penghulu terutama dalam setiap acara resmi ada terutama dalam acara malewa gala atau pengukuhan gelar, selain itu juga biasa dipakai oleh para mempelai pria dalam acara majlis perkawinan yang masyarakat setempat menyebutnya baralek dan juga dipergunakan dalam pertunjukan silat."},
            {"Badik Tumbuk Lado", "Kepulauan Riau", "https://gpswisataindonesia.files.wordpress.com/2014/09/25c32-senjata-kep2briau.png?w=640&h=480", "Badik Tumbuk Lado merupakan senjata tradisional yang berasal dari Kepulauan Riau. Badik sendiri merupakan sebutan untuk senjata tradisional yang dikenal di kalangan masyarakat bugis dan beberapa daerah di Sumatera. Sedangkan, Tumbuk Lada atau Tumbuk Lado (Riau) adalah senjata tradisional masyarakat Melayu dan masyarakat Semenanjung Melayu.\n" +
                    "\n" + "Badik Tumbuk Lado adalah sejenis senjata tikam berukuran 27 sampai 29 cm dan lebarnya sekitar 3.5 sampai 4 cm. Senjata ini memiliki kesamaan dengan badik Bugis, hanya berbeda dalam bentuk dan motif sarung badiknya saja."},
            {"Tombak Trisula", "Sumatra Selatan", "https://i1.wp.com/asyraafahmadi.com/wp-content/uploads/2017/11/tombak-trisula-11.jpg?resize=960%2C720&ssl=1", "Tombak Trisula merupakan senjata tradisional khas Sumatra Selatan, Palembang tepatnya. Senjata tradisional ini konon merupakan senjata pertama yang didaulat pusaka Sumatera Selatan dan kerap menjadi ikon budaya provinsi. Selain itu, merupakan peninggalan dari kejayaan Kerajaan Sriwijaya yang pernah berkuasa pada abad ke-7 hingga awal abad ke-13 M.\n" + "\n" + "Bentuknya ialah sebuah tombak dengan tiga mata tajam di bagian ujungnya. Panjang tombak ini setinggi orang dewasa, yaitu sekitar 180 cm dan dahulu senjata ini digunakan oleh prajurit kerajaan Sriwijaya sebagai senjata utama. Pada kedua sisinya  yaitu sisi ujung atas dan bawah tombak terdapat mata tombak."},
            {"Kujang", "Jawa Barat", "https://i0.wp.com/hidupsimpel.com/wp-content/uploads/2017/05/kujangwww_silatdevelopmentcentre_com.jpg?resize=640%2C478", "Kujang merupakan senjata tradisional dari Jawa Barat yang mana oleh masyarakat Sunda disakralkan dan dianggap magis. Kujang menurut masyarakat Jawa Barat berasal dari bahasa sunda kuno yaitu kata Kudi dan Hyang.\n" +
                    "\n" +
                    "Kudi yang berarti Senjata dengan kekuatan gaib sedangkan Hyang berarti dewa atau masyarakat sunda mengartikannya kedudukan yang di atas Dewa. Berarti Kujang adalah pusaka yang mememiliki kekuatan magis yang kekuatannya berasal dari para dewa.\n" +
                    "\n" +
                    "Ukurannya senjata kujang biasanya berkisar antara 20 sampai 25 cm dan digunakan sebagai perlengkapan peralatan pakaian laki-laki.\n" +
                    "\n" +
                    "Peneliti menyimpulkan bahwasanya dari bentuk kujang, kira-kira senjata ini diperkenalkan oleh nenek moyang Sunda yaitu sebelum abad 8 dan 9, namun ada juga pendapat bahwasanya kujang dibuat pada abad 8 dan 9."},
            {"Golok", "Jakarta", "https://kerisku.id/wp-content/uploads/2017/12/DSC_8598.jpg", "Golok merupakan senjata tradisional Betawi (DKI Jakarta) yang paling terkenal. Senjata tersebut sering dijadikan aksesoris keseharian busana adat Betawi oleh kaum pria. Golok terselip pada ikat pinggang hijau dan dipakai saat bekerja atau sedang bepergian sebagai alat menjaga diri.\n" +
                    "\n" + "Golok khas Betawi memiliki satu bagian mata yang tajam. Sementara satu bagian lainnya tidak tajam. Ia juga dilengkapi dengan serangka yang dipakai pada saat golok tidak sedang digunakan."},
            {"Clurit", "Jawa Timur", "http://www.tahupedia.com/img/uploaded/post/post_9/clurit.jpg", "Clurit atau celurit merupakan senjata tradisional yang berasal dari daerah Madura, Jawa Timur. Clurit diyakini berasal dari legenda pak Sakera / Sakerah, seorang mandor tebu dari Pasuruan yang menjadi salah satu tokoh perlawanan terhadap penjajahan Belanda. Beliau dikenal tak pernah meninggalkan Celurit dan selalu membawa / mengenakannya dalam aktifitas sehari-hari, dimana saat itu digunakan sebagai alat pertanian / perkebunan. Beliau berasal dari kalangan santri dan seorang muslim yang taat menjalankan agama Islam.\n" +
                    "\n" +
                    "Pak Sakera melakukan perlawanan atas penindasan penjajah. Setelah pak Sakerah tertangkap dan dihukum gantung di Pasuruan, Jawa Timur, beliau dimakamkan di Kota Bangil. Atau tepatnya di wilayah Bekacak, Kelurahan Kolursari, daerah paling selatan Kota Bangil. Tindakan penjajah tersebut ternyata menimbulkan kemarahan orang-orang Madura, dan mulai berani melakukan perlawanan pada penjajah dengan senjata andalan meraka adalah Celurit. Sehingga Celurit mulai beralih fungsi menjadi simbol perlawanan, simbol harga diri serta strata sosial."},
            {"Dohong", "Kalimantan Barat", "https://kerisku.id/wp-content/uploads/2017/12/Dohong-Dayak.jpg", "Masyarakat Dayak Ngaju di Kalimantan Barat memiliki senjata tradisional yang bernama Dohong. Dohong adalah sebuah mata tombak yang dapat pula digunakan sebagai pisau. Panjangnya sekitar 8 inch dan dipercaya sebagai senjata tradisional Dayak yang paling tua. Jika digunakan sebagai pisau, dohong akan dilengkapi dengan gagang bulat dan sebuah serangka yang terbuat dari kayu. Dahulunya, Dohong digunakan sebagai senjata perang. Namun kini ia lebih sering dipakai sebagai alat pemotong tali pusar bayi yang baru lahir dan sebagai alat untuk menyembelih hewan korban. Dengan kegunaan tersebut, Dohong saat ini umumnya hanya dimiliki oleh Pisur atau Ketua adat Dayak."},
            {"Mandau", "Kalimantan Timur", "http://3.bp.blogspot.com/_ihi5UU95bSo/S8_bY4QuMFI/AAAAAAAAACg/hDe9OOto20o/s1600/kumpang+mandau.jpg", "Mandau merupakan senjata tradisional suku dayak yang dipergunakan oleh Raja-Raja atau kepala suku saja di Provinsi Kalimantan Timur. Karena mandau diyakini merupakan senjata sakral yang sangat dijaga dan dirawat dengan baik oleh pemiliknya. Mandau adalah sejenis dengan parang, dengan panjang 50 cm.\n" +
                    "\n" +
                    "Pada dasarnya, jenis-jenis Mandau pada semua Masyarakat Dayak mempunyai bentuk yang sama. Tetapi ada sedikit perbedaan bila dilihat dari sisi kelengkungan bilahnya, yaitu ada bilah yang agak condong ke belakang.\n" +
                    "\n" + "Ciri khas yang melekat pada senjata tradisional ini yaitu pada ukiran-ukiran pada bilahnya yang tidak terlalu tajam. Banyak juga ditemui mandau dengan ukiran tambahan lubang pada bilahnya dengan ditutupi dengan tembaga dengan tujuan memperindah bilah mandau."},
            {"Keris Bali", "Bali", "https://www.lawas.net/wp-content/uploads/2018/09/Keris-Pusaka-Bali-Luk-11-Kinantah-Emas-Tebal-1.jpg", "Masyarakat Provinsi Bali mengenal banyak sekali jenis senjata tradisional, di antaranya Keris, Tombak, Tiuk, Taji, Kandik, Caluk, Arit, Udud, Gelewang, Trisula, Panah, Penampad, Garot, Tulud, Kis-Kis, dan lain sebagainya. Namun di antara banyak senjata tersebut, yang paling unik dan indah adalah Keris Bali. Secara struktur, keris Bali memiliki kesamaan dengan keris pada umumnya. Hanya saja, pada senjata ini kita dapat menemukan beragam ukiran baik pada bilah, gagang, maupun pada sarung bilah atau carangkanya. Ukiran-ukiran tersebut bisa berupa bentuk dewa, raksasa, pedande (pendeta), penari, dan bentuk pertapa hutan. Bahkan, kita juga dapat menemukan keris Bali dengan tahta emas dan batu mulia."},
            {"Panah dan Busur", "Papua", "https://i0.wp.com/www.romadecade.org/wp-content/uploads/2018/11/87.-Senjata-Tradisional-Papua.jpg?fit=750%2C455&ssl=1", "Dalam perang antar kampung yang hingga kini masih sering berlangsung antar penduduk Papua, kita bisa menemukan sebuah senjata khas yaitu Panah dan Busur. Anak panah terbuat dari bambu dengan mata tulang kangguru, sementara busurnya terbuat dari bilah bambu dengan tali rotan sebagai tali busurnya. Untuk meningkatkan efektifitas serangan, mata panah biasanya akan dioles dengan racun alami yang diambil dari getah pohon sembaru. Panah dan Busur adalah sepasang senjata utama yang selain digunakan untuk berperang, juga dapat dipakai sebagai senjata perburuan."},
            {"Pisau Belati", "Papua Barat", "https://3.bp.blogspot.com/-3ANXeJu8HiQ/WJ_fdLq4IlI/AAAAAAAAfus/Ppqupwaw0JE-sw0nu3SovI3bL2o-8jypQCLcB/s1600/Pisau%2BBelati%2BKhas%2BPapua.jpg", "Senjata tradisional Papua Barat adalah Pisau Belati. Tidak seperti pisau belati yang biasanya kita kenal, pisau Belati yang menjadi senjata tradisional Papua Barat ini terbilang sangat unik.\n" +
                    "\n" + "Bila pada umumnya terbuat dari bilah logam, bilah Belati justru terbuat dari tulang kaki burung endemik Papua yaitu burung Kasuari. Tulang kaki burung ini dipilih karena mudah dibentuk dan ditajamkan tapi tetap memiliki struktur yang kuat. Pada gagang atau pegangan senjata tradisional Papua Barat ini biasanya juga dilengkapi dengan hiasan bulu burung Kasuari atau serat alam."}
    };

    public static ArrayList<Senjata> getListData(){
        Senjata senjata = null;
        ArrayList<Senjata> list = new ArrayList<>();
        for (String[] aData : data) {
            senjata = new Senjata();
            senjata.setNama(aData[0]);
            senjata.setRemarks(aData[1]);
            senjata.setFoto(aData[2]);
            senjata.setDetil(aData[3]);

            list.add(senjata);
        }

        return list;
    }
}
